In [3]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
div.text_cell_render.rendered_html{font-size:22pt;}
div.output {font-size:22pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:22pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

<b><font size="7" color="red">ch10. N차원(Numpy배열)배열 다루기</font></b>

##4.1 할당

In [ ]:
import numpy as np

In [ ]:
a is b

In [7]:
a==b

NameError: name 'a' is not defined

In [5]:
np.all(a==b)

NameError: name 'np' is not defined

In [8]:
## 4.2 얕은 복사 : 뷰

In [10]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
c = a.view() #얕은복사
print(id(a), id(c))

2887422809392 2887446129104


In [18]:
c==a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
c.shape = (2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
c[1,::2]  =[9,9,9]
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 9,  7,  9,  9,  9, 11]])

In [24]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 9,  7,  9,  9,  9, 11]])

# 4.3 깊은복사

In [29]:
import numpy as np

35a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a = np.array([[5,5,15,0],
              [99,6,16,1],
              [20,5,14,0]])

In [34]:
x = a[:,:-1]
x

array([[ 5,  5, 15],
       [99,  6, 16],
       [20,  5, 14]])

In [35]:
x[:,0]= -9 #슬라이싱이 될 때 뷰가 반환됨(얕은복사)

In [39]:
x = a[:, :-1].copy() #깊은복사
c = np.array(a[:, :-1], copy=True)
x

array([[-9,  5, 15],
       [-9,  6, 16],
       [-9,  5, 14]])

In [37]:
a

array([[-9,  5, 15,  0],
       [-9,  6, 16,  0],
       [-9,  5, 14,  0]])

In [ ]:
#5절 고급인덱싱